blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/MyindMedia/styleme-pro/blob/main/info.md
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/MyindMedia/styleme-pro/discussions
    about: Ask questions and discuss ideas with the community
